Feature/rx callbakcks and disable tx
feistjo/CAN pull request #21
Opened 2023-01-19 21:15 UTC by feistjo

Relies on https://github.com/NU-Formula-Racing/timers/pull/4
Adds RX callback, last receive time tracking, and enable/disable TX messages

2023-01-21 23:14 UTC, ChrisUustal requested changes
As discussed, make file cross-compatible with and without arduino using different constructors, one of which uses arduino millis() and the other which takes in a function for getting time as uint32_t

2023-01-21 23:26 UTC, ChrisUustal submitted a review, later dismissed

2023-01-21 23:26 UTC, ChrisUustal commented on include/can_interface.h
> +        last_receive_time_ = millis();
Also add function for getting time since last received relative to current

2023-01-26 03:03 UTC, izo0619 approved these changes

2023-01-26 03:51 UTC, merged