Initial timers bring up
feistjo/CAN pull request #7
Opened 2022-09-11 13:09 UTC by ChrisUustal

Look it over and let me know if you have any issues with the implementation or want any other timer features to be added

2022-09-11 15:45 UTC, izo0619 commented on include/virtualTimer.h
> +		if (millis() >= prevTick + duration)
I think we discussed changing the order here to this, but are we classifying `millis() == prevTick + duration` to be true or false? Previously was `prevTick + interval <= millis()` so just want to make sure we are consistent

2022-09-11 15:49 UTC, izo0619 commented on include/virtualTimer.h
> +		if (func != NULL)
Should we null check func during init instead? And throw error so it doesn't fail silently

2022-09-11 15:56 UTC, ChrisUustal commented on include/virtualTimer.h
> +		if (millis() >= prevTick + duration)
Yeah we definitely want to include millis() == prevTick + duration because otherwise every timer would become offset by 1ms from the intended delay. Eg. if you want a 10ms timer, it would have a prevTick = 0 and duration = 10 and the condition wouldn't be true until millis() > 10, which means it wouldn't fire again until millis() == 11, which then means prevTick = 11 and now it wouldn't tick again until millis() == 22. tl;dr yes this implementation is consistent and desired

2022-09-11 15:59 UTC, ChrisUustal commented on include/virtualTimer.h
> +		if (func != NULL)
Since this library is offering the dual function of both being a task timer and a regular timer library, we allow the user to create a virtualTimer object without an associated function. This guard ensures that, if someone does ever call .tick() on a function without a declared function, it will be handled gracefully. Regardless, yeah we should return false if someone passes a null pointer to init, so I'll add the change there too

2022-09-11 16:19 UTC, izo0619 commented on include/virtualTimer.h
> +				timerArr[arrPos].init(duration, runFunc);
I'm actually a bit lost here, is this doubly linked list a cycle..? Shouldn't the head node's prev be null? And are we trying to insert at the beginning, middle, or of end of the list? And what is the purpose for the tail pointer (looks like it's not used elsewhere as of now)

2022-09-11 16:19 UTC, izo0619 reviewed
See comments

2022-09-11 17:10 UTC, ChrisUustal commented on include/virtualTimer.h
> +				timerArr[arrPos].init(duration, runFunc);
Yeah so how the library is being used right now we only navigate it in one direction from the head to the tail then stop, but I just set it up to support bi-directional navigation and cyclic navigation if we think it'll be useful in the future. I can also remove this if you think it's confusing / unnecessary

2022-09-11 17:35 UTC, izo0619 commented on include/virtualTimer.h
> +				timerArr[arrPos].init(duration, runFunc);
I see. Unless @feistjo has objections, I am for changing it to just be a singly linked list with head pointer. Also it being cyclical makes it difficult to determine the end of the list. I would prefer the code to be as simple as possible (also saves space) for now, we can always update it later if we need additional functionality 🙂

2022-09-11 20:01 UTC, ChrisUustal commented on include/virtualTimer.h
> +				timerArr[arrPos].init(duration, runFunc);
Updated

2022-09-11 20:01 UTC, ChrisUustal commented on include/virtualTimer.h
> +		if (func != NULL)
Updated

2022-09-12 00:45 UTC, izo0619 approved these changes

2022-09-16 20:23 UTC, feistjo requested changes
I made a number of comments - sorry if I'm seeming nitpicky, I'm used to doing and receiving these reviews with these types of comments from my internship. Also, I think you should be using classes instead of structs, and some of your functions are probably long enough that they should be in a cpp file instead of the h file.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +#define VIRTUALTIMERS_H
I prefer #pragma once, but you can make the argument for using these include guards. Based on the C++ guidelines, it looks like you should be more specific than just the name of the file, in case some other library has a file with the same name. Also, it seems like this shouldn't be in the CAN library - we can either make a new library for it, or make a global Formula library containing all of our important libraries, but we shouldn't add dependencies that multiple things might rely on into a random library that needs it.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +#define MAX_TIMERS 16
Why?

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +}virtualTimer_state_E;
enum class is a more C++ way of doing enums than typedef enum - typedef enum is C style code. Also, Google's C++ style guide says to name it something like VirtualTimerState, and the _E in your name is redundant (it's already an enum), as well as confusing for people not used to it. This should also probably just be enum class State defined inside of the VirtualTimer class, which means that it would be a VirtualTimer::State if referenced externally to the class, and prevents name conflicts with other classes.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	TIMER_NOT_STARTED,
Google's C++ style guide says to name these like constants, not macros - kTimerNotStarted instead of TIMER_NOT_STARTED

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +typedef struct virtualTimer_S
I think this should be a class, and the duration should be a constructor argument. You can also set prevTick (which should be named prev_tick_ since it's a member variable) to millis() in the constructor, and then you don't need the init() function.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +		prevTick = millis();
millis() only works on certain platforms (Arduino) - I think it would be better to make the library more general, even though that means you would need to pass the current time to either start or the constructor. Another option, which is how my internship does it, is that the timer gets passed an elapsed_time every time it gets ticked, which means it doesn't at all need to know the absolute time, and can use std::chrono::milliseconds (or something else from std::chrono) to correctly type the time(s) being stored.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	virtualTimer_state_E getTimerState()
Most functions should be named with CapitalizedCamelCase (eg. GetTimerState()) according to the Google C++ style guide - I think it makes sense to follow this for code consistency and good industry habits, but we can discuss, since it looks like the ISO C++ core guidelines don't say how to name functions

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	void addTimer(virtualTimer_S* newTimer)
It's better/safer to pass a virtualTimer_S& reference than a virtualTimer_S* pointer.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	void (*func)(void) = NULL;
I think it's probably better to have the timers be just timers, and handle calling the functions when they expire.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +		if (func != NULL)
I would prefer returning true if expired - then we can do things like saying if(timer.tick()) {timer.reset(); DoSomething();}. This also makes it consistent with hasTimerExpired().

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +}virtualTimer_S;
Having these names at the end of the struct is much more confusing than putting them at the beginning, and I think this should be a class. Also, I would recommend naming it VirtualTimer (Google C++ guidelines), and the _S saying it's a struct seems unnecessary/redundant and potentially confusing for new people, especially if you follow good conventions for naming things.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +				prevTick = millis();
Should the timer automatically reset? The way this is currently implemented, we can't really use it for things like a precharge timer (which only runs once), which would be useful for our timer library.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	virtualTimer_S* nextTimer = NULL;
Why are we making this a linked list? It seems like, especially since the timer group is its own struct that has an array of timers, there isn't that much point to also having it be a linked list, since you can just iterate through the array.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	virtualTimer_S timerArr[MAX_TIMERS];
I'd recommend using a std::array instead of a c-style array - it has features like being able to do bounds checking on access and storing it's own length, which makes it safer to use. Another option is to use std::vector, which is resizeable, and removes the need for a MAX_TIMERS value, which I can easily imagine us exceeding at size 16.

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	virtualTimer_S* headNode = NULL;
you're naming classes/structs, functions, and variables basically the same - classes/structs and most functions should probably be CapitalizedCamelCase, variables should be snake_case, and member variables should be trailing_snake_case_

2022-09-16 20:23 UTC, feistjo commented on include/virtualTimer.h
> +	unsigned long minTimerDuration;
Use uint32_t instead of unsigned long, as it's better defined across platforms. Better yet, since it's a duration, use std::chrono::milliseconds or similar.

2022-09-21 18:28 UTC, ChrisUustal commented on include/virtualTimer.h
> +		if (func != NULL)
Hmm, I bias the other way and prefer to return true if everything is nominal and false if there is an issue as a standard convention. @izo0619 which would you prefer?

2022-09-21 18:32 UTC, ChrisUustal commented on include/virtualTimer.h
> +#define VIRTUALTIMERS_H
Isabel and I talked about making it a separate library, but we thought and it and couldn't think of any PCBs that aren't going to already be using the CAN library, and this gives the option for the CAN library to use the timers functions as well. If you really feel strongly we should make it separate, it just means everyone is going to have to include both libraries every time they write code or we include a generic shared library they can include.

2022-09-21 18:36 UTC, ChrisUustal commented on include/virtualTimer.h
> +#define MAX_TIMERS 16
I just pick some arbitrarily large but not very large number for the maximum number of timers to initialize the array for memory allocation. I may be able to let the user have some way of initializing it to a size they pass in, but this was a straightforward implementation that worked for all the use cases I could think of and reduced calling complexity.

2022-09-21 18:43 UTC, ChrisUustal commented on include/virtualTimer.h
> +}virtualTimer_state_E;
This is implemented according to Tesla coding convention. I am strongly in favor of always having some _X suffix at the end of all typedefs to clearly distinguish them from variable names. Also, maybe this is just my preference, but I find people new to coding are much more likely to be confused by scope resolution operators (::), so I try to avoid them if possible. It appears you have a strong affinity for them, but I do not feel particularly convinced this is the best way to move forward with a user friendly library system. @izo0619 thoughts? Maybe this is just me, in which case I can migrate the implementation.

2022-09-21 18:43 UTC, ChrisUustal commented on include/virtualTimer.h
> +	TIMER_NOT_STARTED,
Again, different styling guideline recommendations. This is correct according to the styling guidelines I have been taught.

2022-09-21 18:44 UTC, ChrisUustal commented on include/virtualTimer.h
> +typedef struct virtualTimer_S
I will look into it

2022-09-21 18:52 UTC, ChrisUustal commented on include/virtualTimer.h
> +		prevTick = millis();
I think this is getting towards the larger conversation of if we want to keep our code as arduino-similar as possible or if we want to move towards more standard embedded libraries. I personally lean towards keeping it more arduino-similar since it makes the code as similar as possible to what someone may have already seen if they have past arduino experience or as they would see in tutorials online, but I also see the argument for standardization to more accurately reflect industry work. @izo0619 thoughts?

2022-09-21 18:55 UTC, ChrisUustal commented on include/virtualTimer.h
> +	virtualTimer_state_E getTimerState()
Yeah it seems like you are very familiar with google styling guidelines, but I think we should agree on which guidelines we want to follow moving forward and base all recommendations off that. @feistjo @izo0619 do you know what the most common C++ styling guidelines are for embedded firmware and does anyone have a particular preference for which guidelines to follow? I'm not familiar with Google's guidelines at all, but I'm happy to move to them if they're generally seen as the industry standard.

2022-09-21 19:01 UTC, ChrisUustal commented on include/virtualTimer.h
> +	void addTimer(virtualTimer_S* newTimer)
If we're comfortable only ever writing in C++, then yeah I can migrate

2022-09-21 19:02 UTC, ChrisUustal commented on include/virtualTimer.h
> +	void (*func)(void) = NULL;
I'm not sure what you mean by this

2022-09-21 19:04 UTC, ChrisUustal commented on include/virtualTimer.h
> +}virtualTimer_S;
Once again, I very strongly prefer to have the _X at the end of all typedefs to clearly distinguish them from variables. I don't see how this would be any more or less confusing for new people.

2022-09-21 19:08 UTC, ChrisUustal commented on include/virtualTimer.h
> +				prevTick = millis();
The library does support this functionality--you would start the timer then check against hasTimerExpired(). However, I assume you mean you'd want a timer that operates in the same way with a function and a duration, but it would only run once, call the function once, then expire. I think that's a good idea, and I can add that functionality.

2022-09-21 19:09 UTC, ChrisUustal commented on include/virtualTimer.h
> +	virtualTimer_S* nextTimer = NULL;
We support users making their own timers then adding them to a group or creating timers exclusively as part of the group in the array. The linked list allows for navigation between the two without requiring intervention from the user.

2022-09-21 19:11 UTC, ChrisUustal commented on include/virtualTimer.h
> +	virtualTimer_S timerArr[MAX_TIMERS];
I'll look into this

2022-09-21 19:12 UTC, ChrisUustal commented on include/virtualTimer.h
> +	virtualTimer_S* headNode = NULL;
This is not a convention I am familiar with. I have no issues with the first two, but something about ending a variable in an underscore seems extremely uncomfortable to me--but maybe that's just my preference.

2022-09-21 19:14 UTC, ChrisUustal commented on include/virtualTimer.h
> +	unsigned long minTimerDuration;
Once again, I don't think your recommendation of migrating to std::chrono is a uniformly good decision we can make without further discussion. I'm going to organize a meeting for us to discuss if moving to a more standard library at the cost of losing the specialized feature arduino offers is a choice we are all in favor of later this week.

2022-10-01 06:04 UTC, izo0619 reviewed
See comments

2022-10-01 06:04 UTC, izo0619 commented on src/virtualTimer.cpp
> +            if (type == Type::kRepeating)
What happens if the timer type is uninitialized? Will it be the same as the one time?

2022-10-01 06:04 UTC, izo0619 commented on src/virtualTimer.cpp
> +VirtualTimerGroup::VirtualTimerGroup()
Maybe I'm unfamiliar with C++ but do we need empty constructors?

2022-10-01 06:04 UTC, izo0619 commented on src/virtualTimer.cpp
> +    new_timer->init(duration_ms, task_func, VirtualTimer::Type::kRepeating);
Does this mean timer group timer types must be kRepeating? In this case, should we check the timer type for the addTimer that takes in a VirtualTimer object?

2022-10-29 21:37 UTC, closed without merging